services:
  school-news-feed-test-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: SchoolNewsFeed
      TZ: UTC
      PGTZ: UTC
    ports:
      - 5431:5432
    volumes:
      - ./environments/docker/postgres/local/data:/var/lib/postgresql/data
    networks:
      - school-news-feed-test-network
networks:
  school-news-feed-test-network:
    name: schoolNewsFeedTestNetwork
    driver: bridge
