services:
  school-news-feed-db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: SchoolNewsFeed
      TZ: UTC
      PGTZ: UTC
    ports:
      - 5432:5432
    volumes:
      - ./environments/docker/postgres/local/data:/var/lib/postgresql/data
    networks:
      - school-news-feed-network
networks:
  school-news-feed-network:
    name: schoolNewsFeedNetwork
    driver: bridge
